### PR TITLE
Implement extra console commands for Zynthian integration

### PR DESCRIPTION
**Pull request by jofemodo**
I've implemented some extra console commands for using Jalv in Zynthian Project:

+ \get_presets => print the list of presets
+ \set_presets <preset_url> => load a preset, printing the list of control port values
+ \get_controls => print the list of control ports with its current values (symbol=value)
+ \info_controls => print the list of control ports, with detailed port info as JSON formated data
+ \set_control <i>, <v> => set the value of control with index <i>

Other small modifications has been done for zynthian integration:

+ Print the "real" jack client name, not only the "desired" one.
+ Comment a call to "sink" function
+ etc.

I hope you find useful these modifications and want to integrate with the master ;-)

### CODE REVIEW

**Comment by drobilla** [comment]
Cool!  I wonder a bit about scope, though.  `get_controls` and `set_control` with an index clearly fit, `get_presets` and `set_presets` seem reasonable enough too, I suppose (though a general tool could do that), but `info_controls` in particula seems a bit questionable to me.  I don't want to step on too slippery a slope that leads to jalv being a general purpose plugin query mechanism with a query result syntax and so on, since other tools can do a much better job of that.

I'll try to look through the code a more thoroughly soon and see how it feels.

**Comment by jofemodo** [comment]
I've implemented the needed functionality for using Jalv as a LV2-plugin standalone host from Zynthian without having to understand/implement "LV2 things" in the zynthian side.

I can understand that "info_controls" is "a bit questionable", but it simplify a lot the things from the Zynthian side, and also, i think, make the whole thing more efficient/fast-to-load, because we avoid to parse the LV2 plugin in 2 different places.

Anyway, we can maintain our separated branch with the specific features, so you only would merge the functionality you feel comfortable with. No problem at all ;-)

**Comment by drobilla** [comment]
Understandable. I think it should be possible, just adding ad-hoc JSON to Jalv itself is... eh.  Hopefully soonish LV2 will support JSON in a more direct and consistent way, so this could probably be done better then...

In any case, yeah, I think cleaning/chopping this up into sensible pieces and merging them along the way is the way to go.

**Comment by jofemodo** [comment]
Nice! It would be great to have JSON support in Lilv ;-)

**Comment by drobilla** [comment]
I added equivalents to most of these commands:

```
         help              Display help message
         controls          Print settable control values
         monitors          Print output control values
         presets           Print available presets
         preset URI        Set preset
         set INDEX VALUE   Set control value by port index
         set SYMBOL VALUE  Set control value by symbol
         SYMBOL = VALUE    Set control value by symbol
```
I tried to make a reasonably clean interface from a human POV, let me know if this works for your use case.

(PR too messy to suffer the Github workflow, hope you don't mind)

**Comment by jofemodo** [comment]
We have implemented all the functionality in the zynthian side, so we can move to use the official jalv master, after solving 2 little problems with preset loading (see PR#30).

**Comment by drobilla** [comment]
Great, thanks

**Pull request closed without merging**
